apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-monitor-backend.fullname" . }}
  labels:
    {{- include "api-monitor-backend.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "api-monitor-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api-monitor-backend.labels" . | nindent 8 }}
    spec:
      containers:
        - name: apimonitor
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 5000
